    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graduation;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Chateau
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RNAME = new javax.swing.JTextField();
        RPASSWORD = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CRPASSWORD = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 90, 64, 31);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 64, 28);
        getContentPane().add(RNAME);
        RNAME.setBounds(150, 90, 156, 31);
        getContentPane().add(RPASSWORD);
        RPASSWORD.setBounds(150, 130, 156, 28);

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 240, 100, 39);

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 240, 100, 39);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 170, 64, 28);
        getContentPane().add(CRPASSWORD);
        CRPASSWORD.setBounds(150, 170, 156, 28);

        jLabel4.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Welcome");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 390, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/4097561067_cc2a4984bf_o.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 300);

        setSize(new java.awt.Dimension(384, 292));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new login().setVisible(true);        // back to login form
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String namee = RNAME.getText();
        String pw = RPASSWORD.getText();
        String cpwd = CRPASSWORD.getText();
        if (!(pw.equals("") && namee.equals("") && cpwd.equals(""))) {
            if (pw.equals(cpwd)) {
                try {
                    try (PrintWriter outn = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\bombo\\Desktop\\Graduation\\src\\graduation\\users.txt", true)))) {
                        outn.println("\n" + namee);
                    }                    
                    try (PrintWriter outp = new PrintWriter(new BufferedWriter(new FileWriter("C:\\Users\\bombo\\Desktop\\Graduation\\src\\graduation\\passwords.txt", true)))) {
                        outp.println("\n" + pw);                        
                    }                    
                    
                    JOptionPane.showMessageDialog(null, "you are added to our database!");
                    graduation.list.jButton5.setVisible(true);
                    dispose();
                } catch (IOException e) {
                    //exception handling left as an exercise for the reader

                }
            } else {
                JOptionPane.showMessageDialog(null, "password is not the same!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "please complete the data!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPasswordField CRPASSWORD;
    public static javax.swing.JTextField RNAME;
    public static javax.swing.JPasswordField RPASSWORD;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
